import Head from "next/head";
// import TextEditor from "@/components/layout/TextEditor";
import dynamic from "next/dynamic";

const TextEditor = dynamic(() => import("../components/layout/TextEditor"), {
  ssr: false,
});

export default function Home() {
  return (
    <>
      <Head>
        <title>Stegosaurus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <TextEditor></TextEditor>
      </div>
    </>
  );
}
