import Head from "next/head";
import Textarea from "@/components/utility/Textarea";

export default function Home() {
  return (
    <>
      <Head>
        <title>Stegosaurus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Textarea></Textarea>
      </div>
    </>
  );
}
